### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by tanzeelrana** [pierredavidbelanger/parseclient#1]
ERROR : 

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I changed the code a little bit to support ServerURL path

My code : 

    import app.parseclient.*;

    import app.parseclient.support.SimpleConfigurations;

    import javax.ws.rs.client.Client;
    import javax.ws.rs.client.ClientBuilder;

    /**
     * Created by tanzeelrana on 3/21/2017.
     */

    public class ParseService {

    private ParseClient parseClient;
    private Client client;
    private Application application;
    private Perspective perspective;

    public ParseService() {

        client = ClientBuilder.newClient(SimpleConfigurations.jerseyWithJackson());

        parseClient = ParseClient.create(client, "https://pacecouriers.com/parse/");

        application = parseClient.application("XXXX").usingRestApiKey("XXXX").usingMasterKey("fmYwFZUt1hl86lCZms31H6TIigyS9lN7qjKxbBkr");

        perspective = application.asAnonymous();

        ObjectResources<ParseObject> gameScores = perspective.withObjects("Patients");

        Iterable<ParseObject> parseObjects = gameScores.query().find();
        for (ParseObject parseObject : parseObjects)
            System.out.println(parseObject.getObjectId());

    }

    }

**Comment by pierredavidbelanger** [comment]
Hi, I am actually surprised someone use this project now that parse.com is down!

This is a very generic error. Most likely you are using a self signed SSL certificate, or a certificate signed with an obscure sub CA, or simply you need to import all intermediate CA and the root CA (in your case `Let's Encrypt Authority X3` and `DST Root CA X3`)

Anyways, this is not a problem with this project at all, but you can paste a stack trace here and I will try to help you. 

You should also have a look at [this SO question](http://stackoverflow.com/questions/9210514/unable-to-find-valid-certification-path-to-requested-target-error-even-after-c)

**Comment by pierredavidbelanger** [comment]
Also, sine someone actually use this project, it may be time for me to refresh it a little and give it some love.

First I will make the same change you did with this `ServerURL`. Also, maybe bump all maven version to their latest released version.

Did you see something elle this project needs ?

**Comment by pierredavidbelanger** [comment]
ParseClient.create now takes an URI to a self hosted Parse Server: 56ebb0b
A little bug fix here if you where using batches: da8548c
Dependencies are bumped to their latest stable version: 81308bc

Also this project is bumped to 0.9.0-SNAPSHOT

Just tel me if you need something else :)

**Comment by tanzeelrana** [comment]
This is awesome man, I see you have a lot of experience with parse. I want to use parse as my back-end database in my spring boot application.  I want to persist my data through JPA just like we can using SQL. I would love to work on it if you like. I have a few applications that use parse and I want to integrate them with spring boot. 

gonna close the ticket, ur previous comments helped and I tested with other servers that did not have security and it worked perfectly fine.

Cheers

**Comment by pierredavidbelanger** [comment]
I really like your idea of integrating Parse Server as Spring Boot module.
I can already see Parse users APIs as a Spring Security module.
And Parse classes APIs as a Spring JPA module.
It would be a lot of job, but it is doable.

**Comment by tanzeelrana** [comment]
I am using parse users api in my spring app but not as a spring security module. I am not as experienced as you are but I can surely work on it with you and try to catch up speed if you think of starting the project. I can be reached at tanzeelrana@cmail.carleton.ca

Cheers

**Comment by pierredavidbelanger** [comment]
Ive already started something :)
https://github.com/pierredavidbelanger/parse-spring-boot

There is not much doc right now, also everything may not be released to Maven yet.

**Comment by tanzeelrana** [comment]
I tried to use parse4J in my spring boot app and I somehow ended up with having only one session. anyone else trying to access the app automatically is logged in by some other user's auth. I'm not sure how I will provide session management and authentication for all my app users and maintain the integrity. Is parse-spring-boot authentication working ?

**Comment by pierredavidbelanger** [comment]
parse4J is indeed intended for single user environnement (client side, like an Android app).

This project (ParseClient) was create by the need for a multi-user server-side environnement.
But it is still a low level library, with no intention or bias toward a framework/library or an other (even the JAX-RS implementation is swappable).

Now, with [parse-spring-boot](https://github.com/pierredavidbelanger/parse-spring-boot), the goal is to ease the integration of this project (ParseClient) into an application, with opinionated automatic decisions and bias toward Spring Boot.

Right now, only [parse-spring-boot](https://github.com/pierredavidbelanger/parse-spring-boot) is working. This is the foundation library upon which I will base other libraries , like `parse-security-spring-boot-starter` (a Spring Security starter on top of Parse users/roles), or `parse-data-spring-boot-starter` (a Spring Data starter on top of Parse classes).

So, indeed, the next library I will try to implement is `parse-security-spring-boot-starter`, that will gives authentication, authorization and session management base on Parse to a Spring Boot application.

**Comment by tanzeelrana** [comment]
awesome! looking forward to it. I will scrap parse4J and get my project's implementation with this parse-spring-boot and implement the security once you implement it. Thanks again. it will be interesting and educational to read through your `parse-security-spring-boot-starter` code. I was thinking of implementing it but was not confident enough that my design was the right way to go.
